services:
        - docker:stable-dind
stages:
        - pull the code
        - build jar
        - build docker image
        - run docker container

pull:
        stage: pull the code
        before_script:
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - git pull git@gitlab.cs.ttu.ee:glkomi/backend4cash.git origin ${CI_COMMIT_REF_NAME}


build jar:
        stage: build jar
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - mvn install -Dspring.profiles.active=$SPRING_ACTIVE_PROFILE

build docker:
        stage: build docker image
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - docker build --build-arg SPRING_ACTIVE_PROFILE=$SPRING_ACTIVE_PROFILE -t $IMAGE_NAME .

run:
        stage: run docker container
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
                - docker stop $APP_NAME
                - docker container rm $APP_NAME
        script:
                - docker container run -d --name $APP_NAME --net=$NETWORK_NAME --net-alias=$APP_NAME -p $PORT:8080 -e SPRING_PROFILES_ACTIVE=$SPRING_ACTIVE_PROFILE $IMAGE_NAME
