stages:
        - pull the code
        - build jar
        - build docker image
        - stop current container
        - remove stopped container
        - run docker container

pull:
        stage: pull the code
        before_script:
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - git reset --hard HEAD
                - git pull git@gitlab.cs.ttu.ee:glkomi/backend4cash.git ${CI_COMMIT_REF_NAME}


build jar:
        stage: build jar
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - mvn clean install -Dmaven.test.skip=true -Dspring.profiles.active=$SPRING_ACTIVE_PROFILE

build docker:
        stage: build docker image
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - docker build --build-arg SPRING_ACTIVE_PROFILE=$SPRING_ACTIVE_PROFILE -t $IMAGE_NAME .

stop current:
        stage: stop current container
        # allow failure cause sometimes there might not be any container with given name running
        allow_failure: true
        script:
                # cool shell magic
                - docker stop $(docker ps -f "name=backend4cash" -q)


remove current:
        stage: remove stopped container
        allow_failure: true
        script:
                # a to print all containers, cause otherwise the one we've just stopped wont appear
                # (found out the hard way)
                - docker container rm $(docker ps -af "name=backend4cash" -q)

run:
        stage: run docker container
        before_script:
                - source .${CI_COMMIT_REF_NAME}.env
                - cd /home/ubuntu/bits4cash/backend4cash
        script:
                - docker container run -v ~/logs4cash:/app/logs -d --name $APP_NAME --net=$NETWORK_NAME --net-alias=backend4cashdev -p $PORT:8080 -e SPRING_PROFILES_ACTIVE=$SPRING_ACTIVE_PROFILE $IMAGE_NAME
