server:
  servlet:
    context-path: /api
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${172.21.0.4:localhost}:3306/bits4data
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: vovan
logging:
  file:
    path: ./logs
