server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://mysql:3306/bits4data?createDatabaseIfNotExist=true
    username: root
    password: vovan
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: root
      password: vovan
    realmImportFile: vovan-realm.json
  # This for later when i get the actual Ks
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri:
  #         jwk-ser-uri:

