#server:
#  servlet:
#    context-path: /api
#spring:
#  jackson:
#    default-property-inclusion: non_null
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        temp:
#          use_jdbc_metadata_defaults : false
#    hibernate:
#      ddl-auto: create
#  datasource:
#    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 # this one is in memory
#    url: jdbc:h2:./h2/heroes;AUTO_SERVER=TRUE # this one is on the disk, notice the h2 folder and contents it creates
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#  h2:
#    console:
#      #      this enables http://localhost:8080/h2-console
#      enabled: true
##  profiles:
##    active: default
#logging:
#  file:
#    path: ./logs



# vvv do not comment these  vvv
jwt:
  secret: secret
  durationMinutes: 120
coins:
  updating: true
  cron: 0 0 * * * *
# ^^^ do not comment these  ^^^


# upper is for local testing, bottom is for server



server:
  port: 8080
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/vovan.p12
    key-store-password: vovtech
    key-alias: vovtech

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://mysql:3306/bits4data?createDatabaseIfNotExist=true
    username: root
    password: vovan 

trust:
  store: classpath:keystore/vovan.p12
  password: vovtech
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
  # This for later when i get the actual Ks
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri:
  #         jwk-ser-uri: