#server:
#  servlet:
#    context-path: /api
#spring
#
#
#
#
#
##  jooq:
##    sql-dialect=org:
##      hibernate:
##        dialect:
##          MySQLDialect:
##  #jackson:
##    #default-property-inclusion: non_null
##  datasource:
##    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 # this one is in memory
##    url: jdbc:mysql://mysql:3306/bits4data # this one is on the disk, notice the h2 folder and contents it creates
##
##    username: root
##    password: vovan
#logging:
#  file:
#    path: ./logs
#
